[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
fs_permissions = [{ access = "read", path = "./testdata"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Network configurations
[rpc_endpoints]
sepolia = "https://sepolia.drpc.org"

[etherscan]
sepolia = { key = "8V7XSJCZCSSIVA27MMTH3QXNWUSPCARKNZ" }

[dependencies]
"@openzeppelin-contracts" = "5.0.1"
forge-std = "1.9.4"
risc0-ethereum = { version = "2.0.0", url = "https://github.com/vlayer-xyz/risc0-ethereum/releases/download/v2.0.0-soldeer/contracts.zip" }
vlayer = "1.0.2"

[soldeer]
# whether soldeer manages remappings
remappings_generate = false
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false
